version: '3.5'

services:
  postgres:
    image: postgres:9.6.24-alpine3.15
    container_name: cointracker_backend_db
    env_file:
      - ./backend/.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - coin_net

  backend:
    container_name: cointracker_backend
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - coin_net

networks:
  coin_net:

volumes:
  postgres:
